version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "arda1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
    - backend
    volumes:
      - sqlserverdata:/var/opt/mssql

  webapi:
    build: .
    depends_on:
      - sqlserver
    environment:
      - DockerConn=${DockerConn}
      - APIKEY=${APIKEY}
      - ROUTE=${ROUTE}
      - MAX_PAGE=${MAX_PAGE}
      - ROUTE_UPCOMING=${ROUTE_UPCOMING}
    ports:
      - "5015:80"
    networks:
      - backend
volumes:
  sqlserverdata:
networks:
  backend: